version: "3"

services:
  app:
    build:
      context: .
      args:
        DEV: "true"
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /etc/keyfile.json
    command: bash -c "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0 --port 8080"
    volumes:
      - ./app:/app/
      - ./alembic:/app/alembic
      - ./pyproject.toml:/app/pyproject.toml
      - ./alembic.ini:/app/alembic.ini
      - ./docker/entrypoint.sh:/app/entrypoint.sh
      - ./images:/data
      - ./keyfile.json:/etc/keyfile.json
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
